services:
  web:
    build: .
    ports:
      - "8000:5000"
  postgres:
    image: "postgres:15.3-alpine3.18"
    container_name: ${PG_CONTAINER}
    restart: always
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "${PG_PORT}:${PG_PORT}"
    networks:
      - postgres

  pgadmin:
    container_name: ${PGADMIN_CONTAINER}
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin

    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    restart: unless-stopped

  neo4j:
      container_name: ${NEO4J_CONTAINER}
      image: neo4j:5.9.0
      restart: unless-stopped
      ports:
        - ${NEO4J_PORT}:${NEO4J_PORT}
        - ${NEO4J_BOLT_PORT}:${NEO4J_BOLT_PORT}
      volumes:
        - neo4j:/conf
        - neo4j:/data
        - neo4j:/import
        - neo4j:/logs
        - neo4j:/plugins
      environment:
        # Raise memory limits
        - NEO4J_dbms_memory_pagecache_size=1G
        - NEO4J_dbms.memory.heap.initial_size=1G
        - NEO4J_dbms_memory_heap_max__size=1G
        - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD}

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    pgadmin:
    neo4j: